services:
  netbox-hub:
    image: ghcr.io/miniz3210/netbox-hub:latest
    build: .
    container_name: netbox-hub
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./netbox-hub/.env
